---
# Handlers for common role

- name: restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
  become: true 